package com.gasolinerasoledadsacv.view.contratos;

import com.gasolinerasoledadsacv.controller.ContratoJpaController;
import com.gasolinerasoledadsacv.controller.EmpleadoJpaController;
import com.gasolinerasoledadsacv.entity.Contrato;
import com.gasolinerasoledadsacv.entity.Empleado;
import com.gasolinerasoledadsacv.enums.PersistenceEnum;
import com.gasolinerasoledadsacv.util.DateUtil;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ListadoContratosView extends javax.swing.JFrame {

    private final EntityManagerFactory emf = Persistence.createEntityManagerFactory(PersistenceEnum.PERSISTENCE_UNIT_NAME.getValue());
    private EmpleadoJpaController empleadoJpaController;
    private ContratoJpaController contratoJpaController;
    private String numEmpleado;

    public ListadoContratosView(String numEmpleado) {
        initComponents();
        this.numEmpleado = numEmpleado;
        this.llenarTabla(numEmpleado);
    }

    protected void llenarTabla(String numEmpleado) {
        //Llenar tabla
        try {
            contratoJpaController = new ContratoJpaController(emf);
            empleadoJpaController = new EmpleadoJpaController(emf);
            Empleado empleado = empleadoJpaController.findByNumeroEmpleado(numEmpleado);
            labelEmpleado.setText(empleado.getNumeroEmpleado() + " - " + empleado.getNombre() + " " + empleado.getApellidoPaterno() + " " + empleado.getApellidoMaterno());
            List<Contrato> listaContrato = contratoJpaController.findByEmpleado(empleado);
            DefaultTableModel model = (DefaultTableModel) tablaContratos.getModel();
            model.setRowCount(0);
            AtomicInteger numContrato = new AtomicInteger(1);
            listaContrato.forEach(contrato -> {
                model.addRow(new Object[]{contrato.getIdContrato(), numContrato.getAndIncrement(), DateUtil.formatDefault(contrato.getFechaInicial()), DateUtil.formatDefault(contrato.getFechaFinal()), DateUtil.substract(contrato.getFechaInicial(), contrato.getFechaFinal()), contrato.getFechaFiniquito() != null ? DateUtil.formatDefault(contrato.getFechaFiniquito()) : ""});
            });
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se pudo cargar la información de los contratos.\nIntentelo más tarde.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaContratos = new javax.swing.JTable();
        labelEmpleado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado de Contratos");
        setResizable(false);

        tablaContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "No. Contrato", "Fecha Inicial", "Fecha Final", "Periodo Contrato", "Fecha Finiquito"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaContratos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tablaContratos);

        labelEmpleado.setText("<Empleado>");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Empleado:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Listado de Contratos");

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contrato.png"))); // NOI18N
        btnNuevo.setText("Nuevo Contrato");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(labelEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnNuevo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelEmpleado))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        NuevoContratoView nuevoContratoView = new NuevoContratoView(numEmpleado, this);
        nuevoContratoView.setVisible(true);
        nuevoContratoView.setTitle("Nuevo Contrato");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        //El usuario debe seleccionar una fila, de lo contrario no se podra mostrar el formulario de eDITAR/gUARDAR
        if (tablaContratos.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idContrato = Integer.parseInt(tablaContratos.getValueAt(tablaContratos.getSelectedRow(), 0).toString());
        NuevoContratoView nuevoContratoView = new NuevoContratoView(idContrato, this);
        nuevoContratoView.setVisible(true);
        nuevoContratoView.setTitle("Editar Contrato");
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEmpleado;
    private javax.swing.JTable tablaContratos;
    // End of variables declaration//GEN-END:variables
}
