package com.gasolinerasoledadsacv.view.empleados;

import com.gasolinerasoledadsacv.controller.EmpleadoJpaController;
import com.gasolinerasoledadsacv.entity.Empleado;
import com.gasolinerasoledadsacv.enums.PersistenceEnum;
import com.gasolinerasoledadsacv.enums.vo;
import com.gasolinerasoledadsacv.util.DateUtil;
import com.gasolinerasoledadsacv.view.contratos.ListadoContratosView;
import java.awt.Font;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ListadoEmpleadosView extends javax.swing.JFrame {

    private final EntityManagerFactory emf = Persistence.createEntityManagerFactory(PersistenceEnum.PERSISTENCE_UNIT_NAME.getValue());
    private EmpleadoJpaController empleadoJpaController;
    private List<Empleado> listaEmpleados;

    public ListadoEmpleadosView() {
        initComponents();
        this.llenarComponentes();
    }

    private void llenarComponentes() {
        //Llenar combobox estatus
        for (String estatus : vo.estatus) {
            jComboBoxEstatus.addItem(estatus);
        }
        this.llenarTabla(jComboBoxEstatus.getItemAt(0));
    }

    protected void llenarTabla(String estatus) {
        //Llenar tabla
        try {
            empleadoJpaController = new EmpleadoJpaController(emf);
            listaEmpleados = empleadoJpaController.findByEstatusOrderByNumEmplead(estatus);
            DefaultTableModel model = (DefaultTableModel) tablaEmpleados.getModel();
            model.setRowCount(0);
            listaEmpleados.forEach(empleado -> {
                model.addRow(new Object[]{empleado.getNumeroEmpleado(), empleado.getNombre(), empleado.getApellidoPaterno(), empleado.getApellidoMaterno(), DateUtil.formatDefault(empleado.getFechaIngreso()), empleado.getEstatus()});
            });
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "No se pudo cargar la información de los empleados.\nIntentelo más tarde.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        jComboBoxEstatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        botonVer = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonNuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado de Empleados");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Empleado", "Nombre", "Apellido Paterno", "Apellido Paterno", "Fecha Ingreso", "Estatus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEmpleados.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 13));
        tablaEmpleados.setRowHeight(25);
        tablaEmpleados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tablaEmpleados);

        jComboBoxEstatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEstatusItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Estatus:");
        jLabel1.setToolTipText("");

        botonVer.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        botonVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ver.png"))); // NOI18N
        botonVer.setText("Ver");
        botonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerActionPerformed(evt);
            }
        });

        botonEditar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        botonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonNuevo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        botonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregarUsuario.png"))); // NOI18N
        botonNuevo.setText("Nuevo Empleado");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Listado de Empleados");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contrato.png"))); // NOI18N
        jButton1.setText("Contratos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 973, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonVer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        NuevoEmpleadoFrame ef = new NuevoEmpleadoFrame(this);
        ef.setTitle("Nuevo Empleado");
        ef.setVisible(true);
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerActionPerformed
        //El usuario debe seleccionar una fila, de lo contrario no se podra mostrar el formulario de Ver
        if (tablaEmpleados.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String numEmpleado = tablaEmpleados.getValueAt(tablaEmpleados.getSelectedRow(), 0).toString();
        VerEmpleadoView view = new VerEmpleadoView(numEmpleado);
        view.setTitle("Ver Empleado");
        view.setVisible(true);
    }//GEN-LAST:event_botonVerActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        //El usuario debe seleccionar una fila, de lo contrario no se podra mostrar el formulario de eDITAR/gUARDAR
        if (tablaEmpleados.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String numEmpleado = tablaEmpleados.getValueAt(tablaEmpleados.getSelectedRow(), 0).toString();
        NuevoEmpleadoFrame ef = new NuevoEmpleadoFrame(numEmpleado, true, this);
        ef.setTitle("Editar Empleado");
        ef.setVisible(true);
    }//GEN-LAST:event_botonEditarActionPerformed

    private void jComboBoxEstatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEstatusItemStateChanged
        this.llenarTabla(evt.getItem().toString());
    }//GEN-LAST:event_jComboBoxEstatusItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //El usuario debe seleccionar una fila, de lo contrario no se podra mostrar el formulario de cONTRATOS
        if (tablaEmpleados.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String numEmpleado = tablaEmpleados.getValueAt(tablaEmpleados.getSelectedRow(), 0).toString();
        VerEmpleadoView view = new VerEmpleadoView(numEmpleado);
        ListadoContratosView contratosView = new ListadoContratosView(numEmpleado);
        contratosView.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public JComboBox<String> getjComboBoxEstatus() {
        return jComboBoxEstatus;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonVer;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxEstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEmpleados;
    // End of variables declaration//GEN-END:variables
}
