package com.gasolinerasoledadsacv.view.relojChecador;

import com.gasolinerasoledadsacv.pojo.RelojPojo;
import com.gasolinerasoledadsacv.util.DateUtil;
import java.util.Date;

public class JPanelReloj extends javax.swing.JPanel implements Runnable {

    private Thread t1;

    public JPanelReloj() {
        initComponents();
        t1 = new Thread(this);
        t1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDia = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        labelDia.setBackground(new java.awt.Color(0, 0, 0));
        labelDia.setFont(new java.awt.Font("Tahoma", 0, 38)); // NOI18N
        labelDia.setForeground(new java.awt.Color(19, 244, 239));
        labelDia.setText("DD.MM.YYYY");
        labelDia.setAlignmentX(0.5F);
        labelDia.setOpaque(true);

        labelHora.setBackground(new java.awt.Color(0, 0, 0));
        labelHora.setFont(new java.awt.Font("Tahoma", 0, 52)); // NOI18N
        labelHora.setForeground(new java.awt.Color(19, 244, 239));
        labelHora.setText("HH:MM:SS PM");
        labelHora.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(labelHora))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(labelDia)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelHora;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Thread t2 = Thread.currentThread();
        while (t2 == t1) {
            RelojPojo relojPojo = DateUtil.getClockHour(new Date());
            labelHora.setText(relojPojo.getHour());
            labelDia.setText(relojPojo.getDay());
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }
}
